# Generated by Django 2.1.4 on 2018-12-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20181221_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hash_name',
            field=models.BigIntegerField(db_index=True, default=0, unique=True),
        ),
    ]
