# Generated by Django 2.1.4 on 2018-12-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_sourceinfo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('W', 'Warning'), ('R', 'Reject'), ('P', 'Publish')], default='N', max_length=1),
        ),
    ]
