# Generated by Django 2.1.4 on 2018-12-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_auto_20181224_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_summary',
            field=models.BooleanField(default=False),
        ),
    ]
