# Generated by Django 2.1.4 on 2018-12-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
